/*quote div at bottom*/
/*OLD QUOTES
, "you have power over your mind - not outside events. realize this, and you will find strength. <br> -marcus aurelius"
, "after your death you will be what you were before your birth. <br> -arthur schopenhauer"
, "hell is other people. <br> -sartre"
, "it is possible to make no mistakes and lose. that is not failure; that is life. <br> -jean-luc picard"
      , "time is an illusion. lunchtime doubly so. <br> -douglas adams"
      , "i aim to misbehave. <br> -malcolm reynolds"
      , "i ain't lookin' for help from on high. that's a long time waitin' for a train don't come. <br> -malcolm reynolds"
      , "the man who passes the sentence ought to swing the sword. <br> -eddard stark"
      , "and in that sleep of death, what dreams may come... <br> -hamlet"
      , "the man in black fled across the desert, and the gunslinger followed. <br> -stephen king"
      , "if we lose our human nature we lose much, but if we lose our bestial nature, we lose everything. <br> -liu cixin"
      , "waste no more time arguing about what a good man should be. be one. <br> -marcus aurelius"
      , "wealth consists not in having great possesions, but in having few wants. <br> -epictetus"
      , "he who has a why to live can bear almost any how. <br> -friedrich nietzsche"
      , "you come at the king, you best not miss. <br> -omar"
      , "it's a wonder to be alive. if you don't understand that, how can you search for anything deeper? <br> -liu cixin"
      , "no - this is nothing. nothing compared to the fear of losing all i have. <br> -shigeo kageyama"
      , "it's always a little harder than you think it's gonna be. <br> -santiago garcia"
      , "with the first link, the chain is forged. <br> -jean-luc picard"
      , "....that's rad. <br> -kazuma kiryu"
      , "everyone is capable of great good and great evil. treat everyone like they're worth giving a chance. <br> -uncle iroh"
      , "it's time for you to look inward, and ask yourself the big questions: who ARE YOU, and what do YOU want? <br> -uncle iroh"
      , "a man needs his rest. <br> -uncle iroh"
      , "i have never subscribed to the theory that political power flows from the barrel of a gun. <br> -jean-luc picard"
      , "the foundation of every state is the education of its youth. <br> -diogenes of sinope"
      , "no, emptiness is not nothingness. emptiness is a type of existence. you must use this existential emptiness to fill yourself. <br> -cixin liu"
      , "screw makin' sense. it's about fighting spirit! <br> -metal bat"
      , "to be neutral does not mean to be indifferent or insensitive. you don't have to kill your feelings. it's enough to kill hatred within yourself. <br> -geralt of rivia"
      , "time is the cruelest force of all. <br> -liu cixin"
      , "for if it's all the rest of us who are killed by the suicide, it's himself who the murderer kills; only he has to do it over, and over, and over. <br> -ursula leguin"

*/    


var quotes = Array(
        "Everything that happens happens as it should, and if you observe carefully, you will see this to be so. <br> -Marcus Aurelius"
      , "The wealth required by nature is limited and is easy to procure; but the wealth required by vain ideals extends to infinity. <br> -Epicurus"
      , "The woods are lovely, dark and deep, <br> but I have promises to keep, <br> and miles to go before I sleep, <br> and miles to go before I sleep... <br> -Robert Frost"
      , "Costs nothing to say something kind. Even less to shut up altogether. <br> -Malcom Reynolds"
      , "This, too, shall pass. <br> -Sanai"
      , "Sometimes the best way to solve your own problems is to help someone else. <br> -Iroh"
      , "If we're going to be damned, let's be damned for what we really are. <br> -Jean-Luc Picard"
      , "Having great power doesn't mean everything works out for you. But that's okay, so long as you make the important choices yourself. <br> -Kageyama Shigeo"
      , "Laugh, and the world laughs with you. Weep, and you weep alone. <br> -Oh Dae-su"
      , "revenge is good for your health, but pain will find you again. <br> -Oh Dae-su"
      , "There can be no justice so long as laws are absolute! Even life itself is an exercise in exceptions. <br> -Jean-Luc Picard"
      , "Pride is not the opposite of shame, but its source. <br> -Iroh"
      , "It's easy to do nothing. It's hard to forgive. <br> -Aang"
      , "Protection and power are overrated. I think you are very wise to choose happiness and love. <br> -Iroh"
      , "It is important to draw wisdom from different places. If you take it from only one place, it becomes rigid and stale. <br> -Iroh"
      , "Thinking about what you can't control only wastes energy and creates its own enemy. <br> -Worf"
      , "What we leave behind is not as important as how we lived. <br> -Jean-Luc Picard"
      , "Of fear and love, I fear not that I will die, but that all I have come to love will perish with me. <br> -Android 16"
      , "In a rich man's house there is no place to spit but his face. <br> -Diogenes of Sinope"
      , "Blushing is the color of virtue. <br> -Diogenes of Sinope"
      , "If you wake up one morning feeling no pain, you know you are dead. <br> -Russian proverb"
      , "The question of whether computers can think is like the question of whether submarines can swim. <br> -Edsger Dijkstra"
      , "Real evil isn't about bending the law to suit justice. Evil is acting out of small, intensely personal experience and losing sight of the bigger picture so often that you never get it back again. <br> -Karen Traviss"
      , "It is foolish to tear one's hair in grief, as though sorrow would be made less by baldness. <br> -Cicero"
      , "The rule of friendship means there should be mutual sympathy between them, each supplying what the other lacks and trying to benefit the other, always using friendly and sincere words. <br> -Cicero"
      , "Gratitute is not only the greatest of virtues, but the parent of all the others. <br> -Cicero"
      , "Time destroys the speculation of men, but it confirms nature. <br> -Cicero"
      , "The greatest of pleasures are only narrowly separated from disgust. <br> -Cicero"
      , "The end justifies the means. But what if there never is an end? All we have is means. <br> -Ursula LeGuin"
      , "Things don't have purposes, as if the universe were a machine where every part has a useful function. What's the function of a galaxy? I don't know if our life has a purpose and I don't see that it matters. What does matter is that we're a part. Like a thread in a cloth or a grass-blade in a field. It is and we are. What we do is like wind blowing on the grass. <br> -Ursula LeGuin"
      , "A machine is more blameless, more sinless even than any animal. It has no intentions whatsoever but our own. <br> -Ursula LeGuin"
      , "Everything dreams. The play of form, of being, is the dreaming of substance. Rocks have their dreams, and the earth changes... <br> -Ursula LeGuin"
      , "A man can endure the entire weight of the universe for eighty years. It is unreality that he cannot bear. <br> -Ursula LeGuin"
      , "While it is always best to believe in oneself, a little help from others can be a great blessing. <br> -Iroh"
      , "There is no escape - we pay for the violence of our ancestors. <br> -Frank Herbert"
      , "There's no real ending. It's just the place where you stop the story. <br> -Frank Herbert"
      , "It's all one big meat grinder, man. Giant gutter in outer space... <br> -Rust Cohle"
      , "Belief can be manipulated. Only knowledge is dangerous. <br> -Frank Herbert"
      , "Love is the most twisted curse of all. <br> -Akutami Gege"
      , "After everything that's happened, how can the world still be so beautiful? Because it is. <br> -Margaret Atwood"
      ,	"In order to maintain our way of living, we must tell lies to each other, and especially to ourselves. <br> -Derrick Jensen"
      ,	"Somehow, Palpatine returned. <br> -Fyodor Dostoevsky"
      , "He who makes a beast of himself gets rid of the pain of being a man. <br> -Hunter S Thompson"
      , "Very few people stood wholly for the law or wholly against it, and so for them the catastrophe of the churn was an annoyance to be avoided or endured, or else a titillation on the newsfeeds. That it was a question of life and death for other people spoke in its favor as entertainment. <br> -James SA Corey"
      , "You can tell you’ve found a really interesting question when nobody wants you to answer it. <br> Ty Franck"
      , "I thought if you told people facts, they'd draw their conclusions, and because the facts were true, the conclusions mostly would be too. But we don't run on facts. We run on stories about things. About people. <br> James SA Corey"
      , "There's the story, then there's the real story, then there's the story of how the story came to be told. Then there's what you leave out of the story. Which is part of the story too. <br> -Margaret Atwood"
      , "Perfection exacts a price, but it's the imperfect who pay it. <br> -Margaret Atwood"
      , "Take what the moment offers. Don’t close doors. Be thankful. <br> -Margaret Atwood"
      , "What am I living for and what am I dying for are the same question. <br> -Margaret Atwood"
      , "Glenn used to say the reason you can't really imagine yourself being dead was that as soon as you say, 'I'll be dead,' you've said the word I, and so you're still alive inside the sentence. And that's how people got the idea of immortality of the soul - it was a consequence of grammar. And so was God, because as soon as there's a past tense, there has to be a past before the past, and you keep going back in time until you get to I don't know, and that's what God is. It's what you don't know - the dark, the hidden, the underside of the visible, and all because we have grammar... <br> -Margaret Atwood"
      );
    
    var rand = quotes[Math.floor(Math.random() * quotes.length)];
    //$("text").text(" " + rand + " ");
   
    $("index.html").ready(function(){
      $("#text").html(rand);
    });
  
